language: python
python:
  - "3.5"
install:
  - ./build.sh
  - pip install -r requirements/requirements.txt
script:
  - python setup.py install
  - nosetests --with-coverage
after_success:
  - coveralls